"""Add column for order table

Revision ID: 9090fa8ef128
Revises: 6e2483aca79e
Create Date: 2024-04-07 10:25:59.424762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9090fa8ef128'
down_revision: Union[str, None] = '6e2483aca79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('payment_message_id', sa.BigInteger(), nullable=True, comment='Payment Message ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'payment_message_id')
    # ### end Alembic commands ###
