"""Add column of payment account status for telegram chat group table

Revision ID: 799782738c42
Revises: 37182576a108
Create Date: 2024-02-04 22:28:11.536792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '799782738c42'
down_revision: Union[str, None] = '37182576a108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('currency_id_fkey', 'currency', type_='foreignkey')
    op.create_foreign_key('currency_id_fkey', 'currency', 'currency', ['parent_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('exchange_rate_telegram_chat_group_id_fkey', 'exchange_rate', type_='foreignkey')
    op.drop_constraint('exchange_rate_currency_id_fkey', 'exchange_rate', type_='foreignkey')
    op.create_foreign_key('exchange_rate_telegram_chat_group_id_fkey', 'exchange_rate', 'telegram_chat_group', ['telegram_chat_group_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key('exchange_rate_currency_id_fkey', 'exchange_rate', 'currency', ['currency_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('currency_id_fkey', 'handling_fee_config_item', type_='foreignkey')
    op.drop_constraint('handling_fee_config_relation_id_fkey', 'handling_fee_config_item', type_='foreignkey')
    op.create_foreign_key('currency_id_fkey', 'handling_fee_config_item', 'currency', ['currency_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key('handling_fee_config_relation_id_fkey', 'handling_fee_config_item', 'handling_fee_config', ['handling_fee_config_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.add_column('telegram_chat_group', sa.Column('payment_account_status', sa.String(length=32), nullable=True, comment="Payment Account Status. Options: ['preparing', 'out_of_stock']"))
    op.drop_constraint('currency_id_fkey', 'telegram_chat_group', type_='foreignkey')
    op.drop_constraint('handling_fee_config_relation_id_fkey', 'telegram_chat_group', type_='foreignkey')
    op.create_foreign_key('handling_fee_config_relation_id_fkey', 'telegram_chat_group', 'handling_fee_config', ['handling_fee_config_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key('currency_id_fkey', 'telegram_chat_group', 'currency', ['currency_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.drop_constraint('telegram_account_relation_account_id_fkey', 'telegram_chat_group_member', type_='foreignkey')
    op.drop_constraint('telegram_account_relation_chat_group_id_fkey', 'telegram_chat_group_member', type_='foreignkey')
    op.create_foreign_key('telegram_account_relation_chat_group_id_fkey', 'telegram_chat_group_member', 'telegram_chat_group', ['chat_group_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key('telegram_account_relation_account_id_fkey', 'telegram_chat_group_member', 'telegram_account', ['account_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('telegram_account_relation_account_id_fkey', 'telegram_chat_group_member', schema='public', type_='foreignkey')
    op.drop_constraint('telegram_account_relation_chat_group_id_fkey', 'telegram_chat_group_member', schema='public', type_='foreignkey')
    op.create_foreign_key('telegram_account_relation_chat_group_id_fkey', 'telegram_chat_group_member', 'telegram_chat_group', ['chat_group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('telegram_account_relation_account_id_fkey', 'telegram_chat_group_member', 'telegram_account', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('currency_id_fkey', 'telegram_chat_group', schema='public', type_='foreignkey')
    op.drop_constraint('handling_fee_config_relation_id_fkey', 'telegram_chat_group', schema='public', type_='foreignkey')
    op.create_foreign_key('handling_fee_config_relation_id_fkey', 'telegram_chat_group', 'handling_fee_config', ['handling_fee_config_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('currency_id_fkey', 'telegram_chat_group', 'currency', ['currency_id'], ['id'], ondelete='SET NULL')
    op.drop_column('telegram_chat_group', 'payment_account_status')
    op.drop_constraint('handling_fee_config_relation_id_fkey', 'handling_fee_config_item', schema='public', type_='foreignkey')
    op.drop_constraint('currency_id_fkey', 'handling_fee_config_item', schema='public', type_='foreignkey')
    op.create_foreign_key('handling_fee_config_relation_id_fkey', 'handling_fee_config_item', 'handling_fee_config', ['handling_fee_config_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('currency_id_fkey', 'handling_fee_config_item', 'currency', ['currency_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('exchange_rate_currency_id_fkey', 'exchange_rate', schema='public', type_='foreignkey')
    op.drop_constraint('exchange_rate_telegram_chat_group_id_fkey', 'exchange_rate', schema='public', type_='foreignkey')
    op.create_foreign_key('exchange_rate_currency_id_fkey', 'exchange_rate', 'currency', ['currency_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exchange_rate_telegram_chat_group_id_fkey', 'exchange_rate', 'telegram_chat_group', ['telegram_chat_group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('currency_id_fkey', 'currency', schema='public', type_='foreignkey')
    op.create_foreign_key('currency_id_fkey', 'currency', 'currency', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
