"""Adjust handling fee config column

Revision ID: c04576b069f2
Revises: 799782738c42
Create Date: 2024-02-05 22:42:09.821222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04576b069f2'
down_revision: Union[str, None] = '799782738c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('handling_fee_config', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_comment='Name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('handling_fee_config', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_comment='Name')
    # ### end Alembic commands ###
