"""Adjust gac column to otp_secret for user table

Revision ID: 452224a6977a
Revises: c04576b069f2
Create Date: 2024-02-15 13:19:43.602353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452224a6977a'
down_revision: Union[str, None] = 'c04576b069f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_active', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='OTP Active'))
    op.add_column('user', sa.Column('otp_secret', sa.String(length=32), nullable=True, comment='OTP Secret'))
    op.drop_column('user', 'gac')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gac', sa.VARCHAR(length=16), autoincrement=False, nullable=True, comment='Google verification code secret_key'))
    op.drop_column('user', 'otp_secret')
    op.drop_column('user', 'otp_active')
    # ### end Alembic commands ###
