"""Add column of exchange amount for cart table

Revision ID: 9b00df8662b6
Revises: 57d802e36157
Create Date: 2024-03-12 16:19:00.478603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b00df8662b6'
down_revision: Union[str, None] = '57d802e36157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('exchange_amount', sa.Float(), nullable=True, comment='Exchange Amount'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'exchange_amount')
    # ### end Alembic commands ###
