"""Add columns for order table

Revision ID: 0eff7b099d95
Revises: 9b00df8662b6
Create Date: 2024-03-15 00:24:14.090641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eff7b099d95'
down_revision: Union[str, None] = '9b00df8662b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('payment_account', sa.String(length=255), nullable=True, comment='Payment Account'))
    op.add_column('order', sa.Column('receive_payment_account_at', sa.DateTime(timezone=True), nullable=True, comment='Receive Payment Account Time'))
    op.add_column('order', sa.Column('receive_receipt_at', sa.DateTime(timezone=True), nullable=True, comment='Receive Receipt Time'))
    op.add_column('order', sa.Column('done_at', sa.DateTime(timezone=True), nullable=True, comment='Done Time'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'done_at')
    op.drop_column('order', 'receive_receipt_at')
    op.drop_column('order', 'receive_payment_account_at')
    op.drop_column('order', 'payment_account')
    # ### end Alembic commands ###
