name: Docker Image CI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: "Docker build"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Test
        run: |
          # ${{ steps.meta.outputs.tags }}
          # ${{ steps.meta.outputs.labels }}
          echo "REGISTRY: ${{ env.REGISTRY }}"
          echo "IMAGE_NAME: ${{ env.IMAGE_NAME }}"
          echo "USER: ${{ vars.CONTAINER_REGISTRY_USER }}"
          echo "TAGS: ${{ steps.meta.outputs.tags }}"
          echo "LABELS: ${{ steps.meta.outputs.labels }}"
          echo "OUTPUTS: ${{ steps.meta.outputs }}"
      - name: Login to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#            context: .
#            push: true
#            tags: ${{ steps.meta.outputs.tags }}
#            labels: ${{ steps.meta.outputs.labels }}
